spring.application.name=git-project-score
spring.threads.virtual.enabled=true
# GitHub API token - provide via environment variable GITHUB_API_TOKEN
git-project-score.github.api.token=${GITHUB_API_TOKEN}

# To avoid users' misusing the API and prevent getting rate limited by Github, we limit the number of results per page to 10.
git-project-score.max-search-page-size=10